### ISSUE TITLE
[Feature]: Request to have the metrics prepended with "AMD"

### ISSUE THREAD

**Issue by rtkgupta** [ROCm/device-metrics-exporter#113]
### Suggestion Description

Use case: For customers with multi gpu hardware, AMD_ gpu metrics can be made easily identifiable like Nvidia does so by adding DCGM_ to all of their metrics.

**Comment by hhk7734** [comment]
I solved it by adding the following to the values.yaml:

```yaml
serviceMonitor:
  metricRelabelings:
    - sourceLabels: [__name__]
      action: replace
      regex: (.*)
      replacement: amd_$1
      targetLabel: __name__
```
